disabled_rules: # rule identifiers to exclude from running
  - class_delegate_protocol
opt_in_rules: # some rules are only opt-in
  - empty_count
  - convenience_type
  - empty_string
  - fatal_error_message
  - file_name
  - first_where
  - modifier_order
  - private_action
  - private_outlet
  - toggle_bool
  - unused_private_declaration
  - array_init
  - block_based_kvo
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
included: # paths to include during linting. `--path` is ignored if present.
  - Sources
  - Tests
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
identifier_name:
  excluded: # excluded via string array
    - id
    - URL
nesting:
    type_level: 3 
reporter: "xcode"
